#!/usr/bin/env python3
"""
SeisWork — Hypoinverse location module
Author : HakimBMKG

Converts catalog → Hypoinverse SUMMARY/ARC format, runs hypoinverse,
parses output back to SeisWork standard catalog CSV.

Reference:
  Klein, F.W. (2002), USGS Open-File Report 02-171
"""

import os
import sys
import shutil
import subprocess
import time

import pandas as pd


CATALOG_COLS = [
    "event_id", "datetime", "lat", "lon", "depth_km",
    "mag", "rms", "nsta", "gap", "method"
]


class HypoinverseLocator:
    """Hypoinverse earthquake location wrapper."""

    def __init__(self, cfg: dict, base_dir: str):
        self.cfg      = cfg
        self.base_dir = base_dir
        self.lcfg     = cfg["locate"]["hypoinverse"]
        self.reg      = cfg["region"]

        self.out_dir = os.path.join(base_dir, "work", "location", "hypoinverse")
        self.log_dir = os.path.join(base_dir, "work", "logs", "hypoinverse")
        os.makedirs(self.out_dir, exist_ok=True)
        os.makedirs(self.log_dir, exist_ok=True)

        self.exec = self._find_exec()

    def _find_exec(self) -> str:
        name = self.lcfg.get("exec", "hypoinverse")
        # PRIORITAS binary bundled core/bin/ (diisi install.sh), repo-relative.
        repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
        for c in (os.path.join(repo_root, "core", "bin", "hypoinverse"),
                  os.path.join(self.base_dir, "core", "bin", "hypoinverse")):
            if os.path.exists(c):
                return c
        return shutil.which(name) or ""

    # ── Write Hypoinverse .sum control file ───────────────────────────────────
    def _write_control(self, arc_file: str, out_file: str) -> str:
        model_file = self.lcfg.get("model_file", "")
        if not os.path.isabs(model_file):
            model_file = os.path.join(self.base_dir, model_file)

        ctrl = f"""* Hypoinverse control file — auto-generated by SeisWork
CRH 1 {model_file}
STA {os.path.join(self.base_dir, self.cfg['locate']['hypoinverse'].get('station_file','config/station.dat'))}
PHS {arc_file}
SUM {out_file}
ARC {out_file.replace('.sum','.arc')}
PRT F
MAG 1
LST 2
POS 1.68
RMS 0.0 2.0
PRN 4
"""
        ctrl_file = os.path.join(self.out_dir, "hypoinverse.inp")
        with open(ctrl_file, "w") as f:
            f.write(ctrl)
        return ctrl_file

    # ── Convert catalog CSV → Hypoinverse PHASE format (simple ARC) ──────────
    def _catalog_to_arc(self, catalog_file: str, phases_file: str) -> str:
        cat = pd.read_csv(catalog_file)
        arc_file = os.path.join(self.out_dir, "input.arc")

        # Try to load picks for phase data
        picks = None
        pick_path = os.path.join(self.base_dir, "work", "catalog", "picks_gamma.csv")
        if os.path.exists(pick_path):
            picks = pd.read_csv(pick_path)
            picks["event_id"] = picks["event_index"].astype(str)

        from seiswork.utils.converter import catalog_to_hypoinverse_arc
        catalog_to_hypoinverse_arc(cat, picks, arc_file)
        return arc_file

    # ── Parse Hypoinverse .sum output ────────────────────────────────────────
    def _parse_sum(self, sum_file: str) -> pd.DataFrame:
        if not os.path.exists(sum_file):
            print(f"[Hypoinverse] Output not found: {sum_file}")
            return pd.DataFrame()
        rows = []
        with open(sum_file) as f:
            for line in f:
                if len(line) < 80 or line.startswith("*"):
                    continue
                try:
                    year = int(line[0:4])
                    mo   = int(line[4:6])
                    day  = int(line[6:8])
                    hr   = int(line[8:10])
                    mn   = int(line[10:12])
                    sec  = float(line[12:17]) / 100.0
                    lat  = float(line[16:20]) / 100.0 + float(line[20:23]) / 6000.0
                    if line[15] == "S":
                        lat = -lat
                    lon  = float(line[23:27]) / 100.0 + float(line[27:30]) / 6000.0
                    if line[22] == "W":
                        lon = -lon
                    dep  = float(line[30:34]) / 100.0
                    mag  = float(line[44:47]) / 100.0 if line[44:47].strip() else float("nan")
                    rms  = float(line[47:51]) / 100.0 if line[47:51].strip() else float("nan")
                    nsta = int(line[39:41]) if line[39:41].strip() else 0
                    rows.append({
                        "event_id" : f"hinv_{year}{mo:02d}{day:02d}{hr:02d}{mn:02d}",
                        "datetime" : f"{year}-{mo:02d}-{day:02d}T{hr:02d}:{mn:02d}:{sec:06.3f}",
                        "lat"      : lat,
                        "lon"      : lon,
                        "depth_km" : dep,
                        "mag"      : mag,
                        "rms"      : rms,
                        "nsta"     : nsta,
                        "gap"      : float("nan"),
                        "method"   : "hypoinverse",
                    })
                except Exception:
                    pass
        return pd.DataFrame(rows, columns=CATALOG_COLS)

    # ── Public entry ──────────────────────────────────────────────────────────
    def run(self, catalog_file: str):
        if not self.exec:
            print("[ERROR] Hypoinverse binary not found.")
            print("        Install from: https://earthquake.usgs.gov/research/software/hypoinverse.php")
            sys.exit(1)

        print("[Hypoinverse] Preparing input files ...")
        t0 = time.time()

        pha_file = os.path.join(self.base_dir, "work", "catalog", "phases.pha")
        arc_file = self._catalog_to_arc(catalog_file, pha_file)
        sum_file = os.path.join(self.out_dir, "output.sum")
        ctrl     = self._write_control(arc_file, sum_file)

        log = os.path.join(self.log_dir, "hypoinverse.log")
        print(f"[Hypoinverse] Running ...")
        with open(log, "w") as logf:
            ret = subprocess.run(
                [self.exec, ctrl],
                stdout=logf, stderr=subprocess.STDOUT,
                cwd=self.out_dir
            )

        catalog_df = self._parse_sum(sum_file)
        if catalog_df.empty:
            print(f"[Hypoinverse] No results. Check: {log}")
            return

        out = os.path.join(self.base_dir, "work", "catalog", "catalog_hypoinverse.csv")
        catalog_df.to_csv(out, index=False)
        catalog_df.to_csv(os.path.join(self.base_dir, "work", "catalog", "catalog_located.csv"), index=False)

        elapsed = time.time() - t0
        print(f"[Hypoinverse] Done. {len(catalog_df)} events → {out}  ({elapsed:.1f}s)")
        return out
