#!/usr/bin/env python3
"""
SeisWork - glass3 phase association module
Author : HakimBMKG

Runs the neic-glass3 `glass-app` binary (USGS NEIC grid-based Bayesian
stacking associator) as a one-shot batch job: writes picks.csv to gpick,
station list, and grid/initialize/input/output config, runs glass-app
until it self-shuts-down, then parses the `*.jsondetect` output into the
SeisWork standard catalog CSV.

glass-app is normally a long-running realtime daemon; here it's driven one
subprocess per run (like REAL) to fit SeisWork's associator interface. See
doc/GlassConfiguration.md in the neic-glass3 source for parameters.

Reference:
  https://github.com/usgs/neic-glass3
"""

import glob
import json
import os
import shutil
import subprocess
import sys
import time

import pandas as pd


CATALOG_COLS = [
    "event_id", "datetime", "lat", "lon", "depth_km",
    "mag", "rms", "nsta", "gap", "method"
]

PICKS_COLS = [
    "event_id", "network", "station", "phase", "pick_time", "prob"
]


class Glass3Associator:
    """glass3 (neic-glass3 glass-app) phase association wrapper."""

    def __init__(self, cfg: dict, base_dir: str):
        self.cfg      = cfg
        self.base_dir = base_dir
        self.gcfg     = cfg["associate"]["glass3"]
        self.reg      = cfg["region"]

        self.cat_dir    = os.path.join(base_dir, "work", "catalog")
        self.glass_dir  = os.path.join(base_dir, "work", "glass3")
        self.log_dir    = os.path.join(base_dir, "work", "logs", "glass3")
        os.makedirs(self.cat_dir,   exist_ok=True)
        os.makedirs(self.glass_dir, exist_ok=True)
        os.makedirs(self.log_dir,   exist_ok=True)

        self.glass_exec = self._find_glass_app()

    # catalog_dir is a public alias for cat_dir (same convention as
    # GammaAssociator.catalog_dir / RealAssociator.cat_dir)
    @property
    def catalog_dir(self):
        return self.cat_dir

    @catalog_dir.setter
    def catalog_dir(self, value):
        self.cat_dir = str(value)
        os.makedirs(self.cat_dir, exist_ok=True)

    def _find_glass_app(self) -> str:
        name = self.gcfg.get("exec", "glass-app")
        if os.path.isabs(name) and os.path.exists(name):
            return name
        repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__),
                                                  "..", "..", ".."))
        bundled = [
            os.path.join(repo_root,     "core", "bin", "glass-app"),
            os.path.join(self.base_dir, "core", "bin", "glass-app"),
        ]
        for c in bundled:
            if os.path.exists(c):
                return c
        return shutil.which(name) or ""

    def _find_tt_files(self) -> tuple:
        """P.trv/S.trv travel-time tables, bundled repo-relative (like REAL's
        tt_db). config/glass3_tt/ is committed to git and regenerated by
        install.sh Step 3, so this should resolve after a normal install."""
        repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__),
                                                  "..", "..", ".."))
        for d in (os.path.join(repo_root, "config", "glass3_tt"),
                  os.path.join(self.base_dir, "config", "glass3_tt")):
            p, s = os.path.join(d, "P.trv"), os.path.join(d, "S.trv")
            if os.path.exists(p) and os.path.exists(s):
                return p, s
        return "", ""

    # ── Load station list ──────────────────────────────────────────────────────
    def _load_stations(self) -> pd.DataFrame:
        sta_file = self.cfg["data"]["station_file"]
        if not os.path.isabs(sta_file):
            sta_file = os.path.join(self.base_dir, sta_file)
        if not os.path.exists(sta_file):
            print(f"[glass3] ERROR: Station file not found: {sta_file}", flush=True)
            sys.exit(1)
        from seiswork.utils.converter import _load_station_df
        df = _load_station_df(sta_file)
        if df.empty:
            df = pd.read_csv(sta_file, sep=r"\s+", header=None,
                              names=["station", "lat", "lon", "elev"])
            df.insert(0, "network", "")
        return df

    # ── stationlist.json (StationInfoList format, see doc/internal-formats/
    #    StationInfoList.md - one StationInfo entry per station) ─────────────
    def _write_stationlist(self, station_df: pd.DataFrame, run_dir: str) -> str:
        entries = []
        for _, r in station_df.iterrows():
            entries.append({
                "Type": "StationInfo",
                "Site": {
                    "Station" : str(r["station"]).strip(),
                    "Channel" : "BHZ",
                    "Network" : str(r["network"]).strip(),
                    "Location": "--",
                },
                "Latitude" : float(r["lat"]),
                "Longitude": float(r["lon"]),
                "Elevation": float(r.get("elev", 0.0) or 0.0),
                "Enable": True,
                "UseForTeleseismic": True,
                "Quality": 1.0,
            })
        path = os.path.join(run_dir, "stationlist.json")
        with open(path, "w") as f:
            json.dump({"Type": "StationInfoList", "StationList": entries}, f)
        return path

    # ── picks.csv -> gpick (space-delimited 20-field global-pick format,
    #    see neic-glass3 parse/src/gpickparser.cpp:11-35) ─────────────────────
    def _picks_to_gpick(self, picks_file: str, run_dir: str) -> str:
        df = pd.read_csv(picks_file)
        df.columns = [c.lower().strip() for c in df.columns]
        ts = pd.to_datetime(df["phase_time"], utc=True, format="mixed")
        input_dir = os.path.join(run_dir, "input")
        os.makedirs(input_dir, exist_ok=True)
        path = os.path.join(input_dir, "picks.gpick")
        with open(path, "w") as f:
            for i, (_, r) in enumerate(df.iterrows()):
                arrival = ts.iloc[i].strftime("%Y%m%d%H%M%S.%f")[:-3]
                phase = str(r["phase_hint"]).strip()
                if phase not in ("P", "S"):
                    continue
                f.write(
                    f"seiswork {i + 1} 1 {r['station']} BHZ {r['network']} -- "
                    f"{arrival} {phase} -1.0000 ? ? ? 1.000 10.000 0.0 0.000000 "
                    f"{r.get('phase_score', 1.0):.3f} 0.000000 0.000000\n"
                )
        return input_dir

    # ── Write grid.d / initialize.d / input.d / output.d / glass.d ───────────
    def _write_configs(self, run_dir: str, input_dir: str) -> str:
        p_trv, s_trv = self._find_tt_files()
        if not p_trv or not s_trv:
            print("[glass3] ERROR: travel-time tables not found in config/glass3_tt/ "
                  "— run install.sh (Step 3 bundles them from neic-glass3).", flush=True)
            sys.exit(1)
        lat_min, lat_max = self.reg["lat_min"], self.reg["lat_max"]
        lon_min, lon_max = self.reg["lon_min"], self.reg["lon_max"]
        depth_max = float(self.reg.get("depth_max", 60.0))
        center_lat = (lat_min + lat_max) / 2.0
        center_lon = (lon_min + lon_max) / 2.0

        resolution_km = float(self.gcfg.get("node_resolution_km", 15.0))
        # Rough row/col count covering the region at the given resolution
        # (1 deg lat ~= 111 km; longitude degrees scaled by cos(latitude)).
        import math
        deg_per_km_lat = 1.0 / 111.19
        deg_per_km_lon = 1.0 / (111.19 * max(0.2, math.cos(math.radians(center_lat))))
        n_rows = max(4, int((lat_max - lat_min) / (resolution_km * deg_per_km_lat)) + 2)
        n_cols = max(4, int((lon_max - lon_min) / (resolution_km * deg_per_km_lon)) + 2)

        n_cut    = int(self.gcfg.get("nucleation_data_count_threshold", 5))
        n_thresh = float(self.gcfg.get("nucleation_stack_threshold", 2.5))
        sd_assoc = float(self.gcfg.get("association_sd_cutoff", 6.0))

        grid_d = {
            "Cmd": "Grid",
            "Name": "SEISWORK",
            "NucleationPhases": {
                "Phase1": {"PhaseName": "P", "TravFile": p_trv},
                "Phase2": {"PhaseName": "S", "TravFile": s_trv},
            },
            "NodeResolution": resolution_km,
            "NumberOfRows": n_rows,
            "NumberOfColumns": n_cols,
            "CenterLatitude": center_lat,
            "CenterLongitude": center_lon,
            "DepthLayers": [min(depth_max, 10.0), depth_max],
            "NumStationsPerNode": int(self.gcfg.get("num_stations_per_node", 10)),
            "NucleationDataCountThreshold": n_cut,
            "NucleationStackThreshold": n_thresh,
            "SaveGrid": False,
            "AzimuthGapTaper": 270.0,
            "MaximumDepth": depth_max,
        }
        initialize_d = {
            "Cmd": "Initialize",
            "MaximumNumberOfHypos": 500,
            "MaximumNumberOfPicks": 20000,
            "MaximumNumberOfPicksPerSite": 200,
            "PickDuplicateWindow": 2.5,
            "NumberOfNucleationThreads": int(self.gcfg.get("n_threads", 2)),
            "NumberOfHypoThreads": int(self.gcfg.get("n_threads", 2)),
            "Params": {
                "NucleationStackThreshold": n_thresh,
                "NucleationDataCountThreshold": n_cut,
                "AssociationStandardDeviationCutoff": sd_assoc,
                "PruningStandardDeviationCutoff": 3.0,
                "DistanceCutoffFactor": 3.0,
                "DistanceCutoffPercentage": 0.9,
                "DistanceCutoffMinimum": 10.0,
                "HypoProcessCountLimit": 25,
                "ReportingDataThreshold": int(self.gcfg.get("reporting_data_threshold", 1)),
            },
            "DefaultNucleationPhase": {"PhaseName": "P", "TravFile": p_trv},
            "AssociationPhases": [
                {"PhaseName": "P", "Assoc": [0.0, 120.0], "TravFile": p_trv},
                {"PhaseName": "S", "Assoc": [0.0, 120.0], "TravFile": s_trv},
            ],
        }
        # ArchiveDirectory must exist before glass-app starts - if missing,
        # movefileto() silently fails after each read, so the input thread
        # re-reads the same file forever and ShutdownWhenNoData never fires
        # (glass-app hangs until killed; confirmed empirically).
        archive_dir = os.path.join(run_dir, "archive")
        os.makedirs(archive_dir, exist_ok=True)
        input_d = {
            "Configuration": "GlassInput",
            "InputDirectory": input_dir,
            "ArchiveDirectory": archive_dir,
            "ShutdownWhenNoData": True,
            "ShutdownWait": int(self.gcfg.get("shutdown_wait", 60)),
            "Format": "gpick",
            "QueueMaxSize": 20000,
            "DefaultAgencyID": "SW",
            "DefaultAuthor": "seiswork",
        }
        output_dir = os.path.join(run_dir, "output")
        os.makedirs(output_dir, exist_ok=True)
        output_d = {
            "Configuration": "GlassOutput",
            "PublicationTimes": [5, 30],
            "PublishOnExpiration": True,
            "OutputDirectory": output_dir,
            "OutputFormat": "json",
            "TimeStampFileName": True,
            "OutputAgencyID": "SW",
            "OutputAuthor": "seiswork",
        }
        glass_d = {
            "Configuration": "glass-app",
            "LogLevel": "warning",
            "ConfigDirectory": run_dir,
            "InitializeFile": "initialize.d",
            "StationList": "stationlist.json",
            "GridFiles": ["grid.d"],
            "InputConfig": "input.d",
            "OutputConfig": "output.d",
        }

        for name, obj in (("grid.d", grid_d), ("initialize.d", initialize_d),
                           ("input.d", input_d), ("output.d", output_d),
                           ("glass.d", glass_d)):
            with open(os.path.join(run_dir, name), "w") as f:
                json.dump(obj, f)

        return os.path.join(run_dir, "glass.d"), output_dir

    # ── Parse *.jsondetect output -> SeisWork standard catalog/picks ─────────
    # glass-app writes "Detection" typed messages (not the "Hypo"/"Event"
    # schemas in doc/internal-formats/ - confirmed empirically):
    #   {"Type":"Detection","ID":str,"Hypocenter":{Latitude,Longitude,Depth,
    #    Time}, "Bayes":float, "Gap":float, "Data":[{Site:{Station,Network},
    #    Time,Phase,AssociationInfo:{Residual,Sigma}}, ...]}
    # Files may be re-published as an event refines, so dedupe by ID, keeping
    # the latest epoch filename prefix ("<epoch>_<ID>.jsondetect").
    def _parse_output(self, output_dir: str):
        files = glob.glob(os.path.join(output_dir, "*.jsondetect"))
        latest_by_id = {}
        for fp in files:
            base = os.path.basename(fp)
            try:
                epoch = int(base.split("_", 1)[0])
            except ValueError:
                epoch = 0
            try:
                doc = json.load(open(fp))
            except Exception:
                continue
            eid = doc.get("ID")
            if not eid:
                continue
            if eid not in latest_by_id or epoch >= latest_by_id[eid][0]:
                latest_by_id[eid] = (epoch, doc)

        cat_rows, pick_rows = [], []
        for eid, (_, doc) in latest_by_id.items():
            hyp = doc.get("Hypocenter", {})
            if not hyp:
                continue
            event_id = f"glass3_{eid}"
            data = doc.get("Data", []) or []
            cat_rows.append({
                "event_id" : event_id,
                "datetime" : hyp.get("Time", ""),
                "lat"      : float(hyp.get("Latitude", float("nan"))),
                "lon"      : float(hyp.get("Longitude", float("nan"))),
                "depth_km" : float(hyp.get("Depth", float("nan"))),
                "mag"      : float("nan"),
                "rms"      : float("nan"),
                "nsta"     : len(data),
                "gap"      : float(doc.get("Gap", float("nan"))),
                "method"   : "glass3",
            })
            for p in data:
                site = p.get("Site", {}) or {}
                assoc = p.get("AssociationInfo", {}) or {}
                pick_rows.append({
                    "event_id" : event_id,
                    "network"  : site.get("Network", ""),
                    "station"  : site.get("Station", ""),
                    "phase"    : p.get("Phase", assoc.get("Phase", "")),
                    "pick_time": p.get("Time", ""),
                    "prob"     : assoc.get("Sigma", float("nan")),
                })
        cat_df  = pd.DataFrame(cat_rows,  columns=CATALOG_COLS)
        pick_df = pd.DataFrame(pick_rows, columns=PICKS_COLS)
        return cat_df, pick_df

    # ── Public entry ───────────────────────────────────────────────────────────
    def run(self, picks_file: str):
        if not self.glass_exec:
            print("[glass3] ERROR: glass-app binary not found. Build it from "
                  "https://github.com/usgs/neic-glass3 (BUILD_GLASS-APP=ON) "
                  "and copy to core/bin/glass-app.", flush=True)
            sys.exit(1)

        print("[glass3] Starting association ...", flush=True)
        t0 = time.time()

        # Re-create dirs in case cat_dir/glass_dir/log_dir were overridden
        # after __init__ (pipeline_runner.py / RealtimeAssociator do this for
        # job/session isolation, same as RealAssociator).
        os.makedirs(self.cat_dir,   exist_ok=True)
        os.makedirs(self.glass_dir, exist_ok=True)
        os.makedirs(self.log_dir,   exist_ok=True)

        run_dir = os.path.join(self.glass_dir, f"run_{int(t0 * 1000)}")
        os.makedirs(run_dir, exist_ok=True)

        station_df = self._load_stations()
        self._write_stationlist(station_df, run_dir)
        print(f"[glass3] {len(station_df)} stations", flush=True)

        input_dir = self._picks_to_gpick(picks_file, run_dir)
        n_picks = sum(1 for _ in open(os.path.join(input_dir, "picks.gpick")))
        print(f"[glass3] {n_picks} picks → {input_dir}", flush=True)

        glass_conf, output_dir = self._write_configs(run_dir, input_dir)

        log_file = os.path.join(self.log_dir, f"glass3_{int(t0)}.log")
        # Hard kill timeout, with margin over ShutdownWait: nucleation/hypo
        # threads must drain the queue before the idle timer even starts, so
        # a multi-day batch can take longer than ShutdownWait alone (2 days /
        # ~2500 picks needed ~60s against a 30s ShutdownWait, confirmed
        # empirically). Realtime cycles use a smaller shutdown_wait and pick
        # snapshot, so this scales down naturally there too.
        wait_s = int(self.gcfg.get("shutdown_wait", 60)) * 3 + 60
        with open(log_file, "w") as logf:
            try:
                # glass-app accepts only one optional arg after the config
                # file (logname or "noconsole", never both) - passing both
                # trips its argc>3 check and prints usage instead of running.
                subprocess.run(
                    [self.glass_exec, glass_conf, "noconsole"],
                    cwd=run_dir, stdout=logf, stderr=subprocess.STDOUT,
                    timeout=wait_s, env={**os.environ, "GLASS_LOG": run_dir},
                )
            except subprocess.TimeoutExpired:
                print(f"[glass3] WARNING: glass-app did not exit within {wait_s}s "
                      "(killed) — output collected so far is still used", flush=True)

        catalog_df, picks_df = self._parse_output(output_dir)

        if catalog_df.empty:
            print("[glass3] No events found.", flush=True)
            return

        out_cat  = os.path.join(self.cat_dir, "catalog_glass3.csv")
        out_pick = os.path.join(self.cat_dir, "picks_glass3.csv")
        catalog_df.to_csv(out_cat,  index=False)
        picks_df.to_csv(out_pick, index=False)

        # Canonical names - downstream converters (NLLoc, HypoDD, ...) look
        # these up regardless of which associator produced them (see
        # GammaAssociator.run / RealAssociator.run).
        catalog_df.to_csv(os.path.join(self.cat_dir, "catalog_associated.csv"), index=False)
        picks_df.to_csv(os.path.join(self.cat_dir, "picks_associated.csv"), index=False)

        elapsed = time.time() - t0
        print(f"[glass3] Done. {len(catalog_df)} events, {len(picks_df)} picks → {out_cat}  ({elapsed:.1f}s)",
              flush=True)
        return out_cat
